### ISSUE TITLE
No DP or DFLANKINDEL FORMAT found

### ISSUE THREAD

**Issue by Phillip-a-richmond** [gymreklab/STRTools#22]
Running dumpSTR on GangSTR v2.4.2 output with this command:

``` 
dumpSTR --vcf AFF2_expanded_GangSTR2.4.vcf \  
--out pathogenic_str_GLS_GangSTR2.4_Filtered \
--min-supp-reads 1     \
--min-call-DP 10     \
--max-call-DP 1000     \
--min-call-Q 0.9     \
--max-call-flank-indel 0.15   \
--max-call-stutter 0.15
```

And I get this error
```
No DP or DFLANKINDEL FORMAT found
```

Which is confusing because my recent GangSTR run has both of these within the FORMAT header and within each line. 

Attached header plus a few lines of the vcf. 

[AFF2.vcf.txt](https://github.com/gymreklab/STRTools/files/3370386/AFF2.vcf.txt)

**Comment by Phillip-a-richmond** [comment]
Removing those options and I get a different error:

```
dumpSTR --vcf AFF2_expanded_GangSTR2.4.vcf --out pathogenic_str_GLS_GangSTR2.4_Filtered --min-supp-reads 1         --min-call-Q 0.9  
Traceback (most recent call last):
  File "/project/6003075/TOOLS/STR_Tools_Environment/bin/dumpSTR", line 11, in <module>
    load_entry_point('strtools==1.0.0', 'console_scripts', 'dumpSTR')()
  File "/project/6003075/TOOLS/STR_Tools_Environment/lib/python3.7/site-packages/strtools-1.0.0-py3.7.egg/dumpSTR/dumpSTR.py", line 377, in main
  File "/project/6003075/TOOLS/STR_Tools_Environment/lib/python3.7/site-packages/strtools-1.0.0-py3.7.egg/dumpSTR/dumpSTR.py", line 190, in ApplyCallFilters
  File "/project/6003075/TOOLS/STR_Tools_Environment/lib/python3.7/site-packages/strtools-1.0.0-py3.7.egg/dumpSTR/dumpSTR.py", line 145, in FilterCall
  File "/project/6003075/TOOLS/STR_Tools_Environment/lib/python3.7/site-packages/strtools-1.0.0-py3.7.egg/dumpSTR/filters.py", line 180, in __call__
  File "/project/6003075/TOOLS/STR_Tools_Environment/lib/python3.7/site-packages/PyVCF-0.6.8-py3.7.egg/vcf/model.py", line 104, in __getitem__
    return getattr(self.data, key)
AttributeError: 'CallData' object has no attribute 'ALLREADS'
```

Is there a test GangSTR2.4 vcf I can work with to see if it's an installation issue?

Thanks,
Phil

**Comment by Phillip-a-richmond** [comment]
(Bump)

**Comment by nmmsv** [comment]
Hi Philip, 
Sorry for the delayed response. STRtools issues fell under our radar for a while and we are getting to them now.
It seems like you are using `--min-supp-reads`, `--max-call-flank-indel`, and `--max-call-stutter` which are inputs that are specific to filtering HipSTR vcf files. Using these flags with GangSTR vcf is not supported, and will cause an error.
Hope this helps.
Please don't hesitate to reopen this issue, or reach out to me if you have any other problems.
Nima
