### ISSUE TITLE
plinkSTR: TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by psychrb** [gymreklab/STRTools#26]
Help with resolving this error????
plinkSTR --vcf xx --fam xyzzy.fam --out stdout --covar cov.txt --sex --logistic --allele-tests --allele-tests-length

Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/py_packages/3.7/bin/plinkSTR", line 11, in <module>
    load_entry_point('strtools==1.0.0', 'console_scripts', 'plinkSTR')()
  File "/hpc/users/birnbr02/.local/lib/python3.7/site-packages/plinkSTR/plinkSTR.py", line 304, in main
    reader = vcf.Reader(open(args.vcf, "rb"))
  File "/hpc/users/birnbr02/.local/lib/python3.7/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()
  File "/hpc/users/birnbr02/.local/lib/python3.7/site-packages/vcf/parser.py", line 342, in _parse_metainfo
    key, val = parser.read_meta(line)
  File "/hpc/users/birnbr02/.local/lib/python3.7/site-packages/vcf/parser.py", line 225, in read_meta
    match = self.meta_pattern.match(meta_string)

TypeError: cannot use a string pattern on a bytes-like object

**Comment by psychrb** [comment]
Resolved!!
